#!/usr/bin/env python3
# -*- coding: utf-8 -*-
u"""Write the Urdu lexicon out as C, for the SAPI engine to read.

Everything the Urdu frontend knows lived in tools/urdu/phones.py, which is
Python and runs offline. The voice a person actually installs never saw any
of it: SAPI hands the engine letters, Urdu does not write its short vowels,
and so the voice guessed at the vowel in every word while a lexicon that knew
it sat unused on disk. کتاب was ktab to the voice and kɪtaːb to the WAVs.

This closes that. The lookup is the whole of what has to cross, and it
crosses as data rather than code: for every word in the lexicon, what
phones.py finally decides -- after the IPA is mapped, after length is
doubled, after the stress rule has run -- is written down as the phoneme
string it ends up being. So the C side does no phonetics at all. It splits
words, normalises the spelling, looks up, and wraps the answer in the
annotation the engine already reads.

Two arrays. A blob of "word\0phones\0" pairs, and an index of offsets into
it, sorted by the word. Python sorts strings by code point and UTF-8 compares
byte for byte in the same order, so the C side binary-searches with strcmp
and gets the same answer. About 2.7 MB for 102,000 words.

The number names go with it, since numbers cannot be a lookup -- there are
infinitely many -- and the hundred words they are built from are the same
hundred either side.

usage: tools/urdu/gen_sapi_lex.py [out.c]
"""

import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numbers as urdu_numbers
import phones

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "sapi", "urdu_lex.c")

HEAD = u'''/* Generated by tools/urdu/gen_sapi_lex.py. Do not edit.

   The Urdu lexicon, as the phonemes the engine speaks rather than as IPA:
   %(n)d words, every one of them already through the whole of
   tools/urdu/phones.py. sapi/urdu_text.c does the looking up.

   blob holds "word\0phones\0" pairs and index holds the offset of each
   word, sorted by the word. Python sorted these by code point and UTF-8
   compares byte for byte in the same order, so a strcmp binary search over
   index finds what Python would have found. */

#include "urdu_lex.h"

const int32_t urdu_lex_count = %(n)d;

'''


def c_string(b):
    """A run of bytes as C string literals, broken into lines.

    Written as octal escapes throughout rather than as characters: the source
    is then ASCII whatever the bytes are, which is the one thing that cannot
    be got wrong by a compiler's idea of the current code page. It triples
    the size of the file and none of the size of the object.
    """
    out, line = [], []
    n = 0
    for c in b:
        line.append("\%03o" % c)
        n += 1
        if n % 20 == 0:
            out.append('"%s"' % "".join(line))
            line = []
    if line:
        out.append('"%s"' % "".join(line))
    return "\n".join(out)


def main(argv):
    out = argv[0] if argv else OUT

    lex = phones.lexicon()
    rows = []
    for w in sorted(lex):
        said = phones.word(phones.OVERRIDE.get(w) or lex[w])
        if said.startswith(u"`[") and said.endswith(u"]"):
            said = said[2:-1]
        if said:
            rows.append((w, said))

    blob, index = bytearray(), []
    for w, said in rows:
        index.append(len(blob))
        blob += w.encode("utf-8") + b"\0" + said.encode("utf-8") + b"\0"

    # The numbers, as the same phonemes. Nought to ninety-nine by value, then
    # the scale words and the two that are not counts at all, in the order
    # urdu_text.c expects them.
    tab = urdu_numbers.table()
    order = [str(i) for i in range(100)] + [
        urdu_numbers.HUNDRED, urdu_numbers.THOUSAND, urdu_numbers.LAKH,
        urdu_numbers.KAROR, urdu_numbers.ARAB, urdu_numbers.KHARAB,
        urdu_numbers.MINUS, urdu_numbers.POINT]
    nums = []
    for k in order:
        said = phones.word(tab.get(k, u""))
        if said.startswith(u"`[") and said.endswith(u"]"):
            said = said[2:-1]
        nums.append(said)

    with io.open(out, "w", encoding="ascii", newline="\n") as f:
        f.write(HEAD % {"n": len(rows)})
        f.write(u"const char urdu_lex_blob[] =\n%s;\n\n"
                % c_string(bytes(blob)))
        f.write(u"const int32_t urdu_lex_index[] = {\n")
        for i in range(0, len(index), 10):
            f.write(u"    " + u", ".join(str(x) for x in index[i:i + 10])
                    + u",\n")
        f.write(u"};\n\n")
        f.write(u"/* Nought to ninety-nine, then sau, hazaar, laakh, karor,\n"
                u"   arab, kharab, minfi and aashaariya. */\n")
        f.write(u"const char *const urdu_num_words[] = {\n")
        for s in nums:
            f.write(u'    "%s",\n' % s.encode("utf-8").decode("ascii", "backslashreplace"))
        f.write(u"};\n")

    print("urdu/gen_sapi_lex: %d words, %.1f MB blob, to %s"
          % (len(rows), len(blob) / 1e6, os.path.relpath(out, ROOT)),
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
