/* The Urdu lexicon the SAPI engine looks words up in.

   sapi/urdu_lex.c is generated by tools/urdu/gen_sapi_lex.py and holds the
   data; sapi/urdu_text.c holds the reading of it. Nothing else includes
   this. */

#ifndef URDU_LEX_H
#define URDU_LEX_H

#include <stdint.h>

/* "word\0phones\0" pairs, and the offset of each word, sorted by the word so
   that a strcmp binary search finds it. */
extern const char    urdu_lex_blob[];
extern const int32_t urdu_lex_index[];
extern const int32_t urdu_lex_count;

/* Nought to ninety-nine by value, then sau, hazaar, laakh, karor, arab,
   kharab, minfi and aashaariya: 108 entries, as phonemes. */
extern const char *const urdu_num_words[];

#define URDU_NUM_HUNDRED  100
#define URDU_NUM_THOUSAND 101
#define URDU_NUM_LAKH     102
#define URDU_NUM_KAROR    103
#define URDU_NUM_ARAB     104
#define URDU_NUM_KHARAB   105
#define URDU_NUM_MINUS    106
#define URDU_NUM_POINT    107

/* Urdu text as one string of `[...]' annotations, or a null pointer if
   nothing in it could be said. The caller frees what comes back. */
char *urdu_annotate(const char *utf8);

#endif
